# -*- coding: utf-8 -*-
"""Lec1_Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eb1M3BvOg5OlBKwVmnkhsVWiCn2JQc_S
"""

print("Hello World")

a="Happy"
b="Birthday"
c=" "
ans= a+c+b
print(ans)

a=int(input("Enter number : "))
b=int(input("Enter number : "))
c=int(input("Enter number : "))
d=int(input("Enter number : "))
e=int(input("Enter number : "))
sum=a+b+c+d+e
print(sum)

a=1000000000000
b=3452485676897
sum=a+b
print (sum)

a=10
b=9
temp=9
b=a
a=temp
print (a)
print(b)

a=10
b=20
a=a+b
b=a-b
a=a-b
print(a)
print (b)

odd=[]
even=[]
for i in range(1,51):
  if(i%2!=0):
    odd.append(i)
  else:
    even.append(i)
print(odd)
print(even)

n=input()
i=0
j=len(n)-1
temp=True
while(i<j):
  if n[i]!=n[j]:
    temp=False
    break;
  i=i+1
  j=j-1
if(temp):
  print("Palindrome")
else:
  print("Not Palindrome")